# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn', models.CharField(max_length=20, verbose_name='单号')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('pay_status', models.IntegerField(choices=[(0, '未支付'), (1, '已支付'), (2, '正在支付')], default=0, verbose_name='订单状态')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 't_order',
            },
        ),
    ]
