# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='书名')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('summary', models.TextField(max_length=100, verbose_name='简介')),
                ('info', models.TextField(max_length=200, verbose_name='作品信息')),
                ('cover', models.ImageField(upload_to='book', verbose_name='封面')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Category', verbose_name='分类')),
                ('tags', models.ManyToManyField(to='content.Tag', verbose_name='标签')),
            ],
        ),
    ]
