# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '小说', 'verbose_name_plural': '小说'},
        ),
        migrations.AlterModelTable(
            name='book',
            table='t_book',
        ),
    ]
