# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 06:56
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20181023_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='book', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='book',
            name='info',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='作品信息'),
        ),
    ]
