# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 01:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20181024_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-add_time'], 'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
    ]
